# Generated by Django 4.1.1 on 2022-09-21 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UrlSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('shortened_url_path', models.CharField(max_length=50)),
                ('submission_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
