# Generated by Django 4.1.1 on 2022-09-21 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_creator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortenedUrlPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortened_url_path', models.CharField(max_length=50)),
                ('in_use', models.BooleanField()),
                ('creation_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
